name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Create empty package-lock.json if it doesn't exist
        run: |
          if [ ! -f package-lock.json ]; then
            echo "{}" > package-lock.json
          fi

      - name: Build
        run: |
          npm run build || (echo "Build failed, checking TypeScript errors" && npx tsc --noEmit && exit 1)

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
